"""Assert each document contains what the code actually produces.

Not a find-and-replace check. The expected strings are generated by calling
the real functions and reading the real keyboards, so a document can only
pass by agreeing with the running bot.
"""
import re, sys, zipfile
sys.path.insert(0, ".")

from app.services import relay
from app.bot.handlers.client import unrouted_notice
from app.bot import keyboards as kb
from app.db.models import Department, WorkItemStatus

def text_of(path):
    xml = zipfile.ZipFile(path).read("word/document.xml").decode("utf-8")
    t = re.sub(r"<[^>]+>", "", xml.replace("</w:p>", "\n"))
    for a, b in [("&amp;","&"),("&lt;","<"),("&gt;",">"),("&quot;",'"'),("&apos;","'")]:
        t = t.replace(a, b)
    # Documents wrap long lines; compare on collapsed whitespace.
    return re.sub(r"\s+", " ", t)

class FakeItem:
    def __init__(self, dept):
        self.department = dept
        self.client_reference = "ACME-1042"

def buttons(markup):
    return [b.text for row in markup.inline_keyboard for b in row]

def strip(label):
    return label.replace("✉ ", "").replace(" ⌄", "").replace(" ⌃", "")

D = "/sessions/hopeful-epic-knuth/mnt/Nexterpay/"
O = "/sessions/hopeful-epic-knuth/mnt/outputs/"

MANUAL = D + "NexterPay Operations Platform - Complete Manual.docx"
SUPPORT = D + "NexterPay - Support Test Script.docx"
BUSINESS = O + "NexterPay - Business Test Script.docx"

fails = []

def check(path, expected, why):
    body = text_of(path)
    for e in expected:
        needle = re.sub(r"\s+", " ", e)
        if needle not in body:
            fails.append(f"{path.rsplit('/',1)[1]}: {why}\n     missing: {needle[:100]}")

# --- the manual quotes the Support side end to end -----------------------
sup = FakeItem(Department.SUPPORT)
check(MANUAL, [
    relay.acknowledgement_text(sup).split("\n")[0],
    relay.acknowledgement_text(sup).split("\n")[-1],
], "the Support acknowledgement")

check(MANUAL, [strip(b) for b in buttons(kb.work_item_actions(1, claimed=False))],
      "the buttons on an open request")
check(MANUAL, [strip(b) for b in buttons(kb.confirm_reply(1))], "the reply preview buttons")
check(MANUAL, buttons(kb.acknowledgement_actions()), "the acknowledgement button")
check(MANUAL, buttons(kb.raise_request_prompt("support")), "the Support front door")
check(MANUAL, buttons(kb.raise_request_prompt("business")), "the Business front door")
check(MANUAL, [s.client_label for s in WorkItemStatus], "the client status wording")
check(MANUAL, [relay.claim_notice_text(sup, "Gavin"),
               relay.claim_notice_text(FakeItem(Department.BUSINESS), "Gavin")],
      "the claim notices")
check(MANUAL, [unrouted_notice(1, Department.SUPPORT).split(".")[0]],
      "the unmatched reply")

# --- each test script quotes its own desk --------------------------------
for path, dept in [(SUPPORT, Department.SUPPORT), (BUSINESS, Department.BUSINESS)]:
    item = FakeItem(dept)
    ack = relay.acknowledgement_text(item)
    check(path, [ack.split("\n")[-1]], f"the {dept.label} acknowledgement tail")
    check(path, [relay.claim_notice_text(item, "Gavin")],
          f"the {dept.label} claim notice")
    check(path, [f"our {dept.label} Team has not been notified"],
          f"the {dept.label} unmatched reply")
    check(path, buttons(kb.raise_request_prompt(dept.value)), f"the {dept.label} front door")
    check(path, [strip(b) for b in buttons(kb.confirm_reply(1))], "the reply preview buttons")

# --- and nothing anywhere still uses the old wording ---------------------
OLD = ["My requests", "Reply to client", "Send to client", "In progress",
       "Waiting on you", "I could not match", "nobody has been notified",
       "looking after this", "The Business team", "anything further to it",
       "with our Support team", "with our Business team", "desk's workload"]
for path in (MANUAL, SUPPORT, BUSINESS):
    body = text_of(path)
    for old in OLD:
        if old in body:
            fails.append(f"{path.rsplit('/',1)[1]}: still contains the old wording {old!r}")

if fails:
    print("FAILED:")
    for f in fails:
        print("  -", f)
    sys.exit(1)
print("All three documents agree with the running code.")
