"""work item header message id

Revision ID: df0ba1ca5cdc
Revises: 5e5dc2c15711
Create Date: 2026-08-25 11:35:58.292075
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'df0ba1ca5cdc'
down_revision = '5e5dc2c15711'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('header_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items', 'header_message_id')
    # ### end Alembic commands ###
