"""initial schema

Revision ID: 71b7b002220b
Revises: 
Create Date: 2026-08-13 13:18:23.686925
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '71b7b002220b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('name', name=op.f('uq_clients_name'))
    )
    op.create_table('reference_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_counter'))
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('operator', 'senior_operator', 'manager', 'administrator', name='staff_role'), nullable=False),
    sa.Column('department', sa.Enum('support', 'finance', 'development', 'business', name='department'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff')),
    sa.UniqueConstraint('telegram_user_id', name=op.f('uq_staff_telegram_user_id'))
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('client', 'operations', name='chat_kind'), nullable=False),
    sa.Column('department', sa.Enum('support', 'finance', 'development', 'business', name='department'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_chats_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats')),
    sa.UniqueConstraint('telegram_chat_id', name=op.f('uq_chats_telegram_chat_id'))
    )
    op.create_index('uq_operations_chat_per_department', 'chats', ['department'], unique=True, sqlite_where=sa.text("kind = 'operations'"), postgresql_where=sa.text("kind = 'operations'"))
    op.create_table('work_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('support', 'finance', 'development', 'business', name='department'), nullable=False),
    sa.Column('source_chat_id', sa.Integer(), nullable=False),
    sa.Column('operations_chat_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=True),
    sa.Column('raised_by_telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('raised_by_name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('original_message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'claimed', 'in_progress', 'waiting_client', 'waiting_internal', 'waiting_third_party', 'escalated', 'completed', 'closed', name='work_item_status'), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='priority'), nullable=False),
    sa.Column('owner_staff_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_work_items_client_id_clients')),
    sa.ForeignKeyConstraint(['operations_chat_id'], ['chats.id'], name=op.f('fk_work_items_operations_chat_id_chats')),
    sa.ForeignKeyConstraint(['owner_staff_id'], ['staff.id'], name=op.f('fk_work_items_owner_staff_id_staff')),
    sa.ForeignKeyConstraint(['source_chat_id'], ['chats.id'], name=op.f('fk_work_items_source_chat_id_chats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_items'))
    )
    op.create_index('ix_work_items_open_by_source', 'work_items', ['source_chat_id', 'status'], unique=False)
    op.create_index(op.f('ix_work_items_reference'), 'work_items', ['reference'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('work_item_created', 'topic_created', 'ownership_claimed', 'ownership_assigned', 'ownership_released', 'status_changed', 'priority_changed', 'internal_note_added', 'client_message_received', 'staff_reply_sent', 'attachment_received', 'work_item_closed', 'work_item_reopened', 'topic_closed', name='event_type'), nullable=False),
    sa.Column('actor_staff_id', sa.Integer(), nullable=True),
    sa.Column('actor_telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_staff_id'], ['staff.id'], name=op.f('fk_events_actor_staff_id_staff')),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name=op.f('fk_events_work_item_id_work_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index('ix_events_work_item_seq', 'events', ['work_item_id', 'id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', 'internal', name='message_direction'), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_name', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name=op.f('fk_messages_work_item_id_work_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('telegram_chat_id', 'telegram_message_id', name='uq_message_identity')
    )
    op.create_index('ix_messages_lookup', 'messages', ['telegram_chat_id', 'telegram_message_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=300), nullable=False),
    sa.Column('file_unique_id', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_attachments_message_id_messages')),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name=op.f('fk_attachments_work_item_id_work_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_index('ix_messages_lookup', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_events_work_item_seq', table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_work_items_reference'), table_name='work_items')
    op.drop_index('ix_work_items_open_by_source', table_name='work_items')
    op.drop_table('work_items')
    op.drop_index('uq_operations_chat_per_department', table_name='chats', sqlite_where=sa.text("kind = 'operations'"), postgresql_where=sa.text("kind = 'operations'"))
    op.drop_table('chats')
    op.drop_table('staff')
    op.drop_table('reference_counter')
    op.drop_table('clients')
    # ### end Alembic commands ###
