"""counterparty codes and supplier link

Adds the four-letter code that leads every reference, and the optional
supplier a ticket is filed against.

Written by hand rather than autogenerated. An earlier migration in this
project was autogenerated against SQLite, reported success, and changed
nothing - so anything touching constraints is spelled out here.

Existing tickets are deliberately left alone. They keep their #1000 form
until someone chooses to renumber them; a reference already quoted in an
email should not change underneath the person holding it.

Revision ID: 9a2c4f1e77b3
Revises: df0ba1ca5cdc
Create Date: 2026-08-30 16:00:00.000000
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '9a2c4f1e77b3'
down_revision = 'df0ba1ca5cdc'
branch_labels = None
depends_on = None

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def upgrade() -> None:
    # The code is nullable: counterparties registered before this migration
    # have none until an administrator assigns one.
    with op.batch_alter_table("clients", naming_convention=NAMING_CONVENTION) as batch:
        batch.add_column(sa.Column("code", sa.String(length=4), nullable=True))

    # A unique index rather than a separate unique constraint plus a plain
    # index: that is what `unique=True, index=True` on the model produces, and
    # `alembic check` compares the two. Uniqueness is enforced either way, but
    # a schema that does not match the model is a trap for whoever autogenerates
    # the next migration.
    op.create_index("ix_clients_code", "clients", ["code"], unique=True)

    with op.batch_alter_table("work_items", naming_convention=NAMING_CONVENTION) as batch:
        batch.add_column(sa.Column("supplier_id", sa.Integer(), nullable=True))
        batch.add_column(sa.Column("client_code", sa.String(length=4), nullable=True))
        batch.add_column(sa.Column("supplier_code", sa.String(length=4), nullable=True))
        batch.create_foreign_key(
            "fk_work_items_supplier_id_clients", "clients", ["supplier_id"], ["id"]
        )

    # Filing a ticket under a supplier is recorded like any other change, so
    # the event type needs the new value. On Postgres that is a real enum
    # type; on SQLite the column is a plain VARCHAR and needs nothing.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE event_type ADD VALUE IF NOT EXISTS 'supplier_filed'")

    # Backfill the client code onto existing tickets where the counterparty
    # already has one. Harmless today, because none do yet, and it means a
    # code assigned before this deploy is not silently ignored.
    op.execute(
        "UPDATE work_items SET client_code = ("
        "  SELECT code FROM clients WHERE clients.id = work_items.client_id"
        ") WHERE client_code IS NULL"
    )


def downgrade() -> None:
    # Postgres cannot remove a value from an enum type. Left in place; it is
    # harmless, and dropping and recreating the type would require rewriting
    # every row in the events table.
    with op.batch_alter_table("work_items", naming_convention=NAMING_CONVENTION) as batch:
        batch.drop_constraint("fk_work_items_supplier_id_clients", type_="foreignkey")
        batch.drop_column("supplier_code")
        batch.drop_column("client_code")
        batch.drop_column("supplier_id")

    op.drop_index("ix_clients_code", table_name="clients")
    with op.batch_alter_table("clients", naming_convention=NAMING_CONVENTION) as batch:
        batch.drop_column("code")
